INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (14, 'Dashboard', 'Dashboard', 'sidebar', 'LEVEL_1', 1, 'flaticon-025-dashboard', 'Dashboard', 'Dashboard', false, NULL, NULL, 0, 'dashboard');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (15, 'Administration', 'Administration', 'sidebar', 'LEVEL_1', 1000000000, 'flaticon-013-checkmark', 'Administration', 'Administration', false, NULL, NULL, 0, NULL);
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (16, 'User Management', 'User Management', 'sidebar', 'LEVEL_1', 1, NULL, 'User Management', 'User Management', false, NULL, 15, 0, 'users');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (17, 'Install Module', 'Install Module', 'sidebar', 'LEVEL_1', 2, NULL, 'Install Module', 'Install Module', false, NULL, 15, 0, 'bootstrap-modules');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (18, 'Roles & Privileges', 'Roles & Privileges', 'sidebar', 'LEVEL_1', 3, NULL, 'Roles & Privileges', 'Roles & Privileges', false, NULL, 15, 0, 'roles');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (19, 'Organization Unit', 'Organization Unit', 'sidebar', 'LEVEL_1', 4, NULL, 'Organization Unit', 'Organization Unit', false, NULL, 15, 0, 'organisation-unit');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (20, 'Application Codeset', 'Application Codeset', 'sidebar', 'LEVEL_1', 5, NULL, 'Application Codeset', 'Application Codeset', false, NULL, 15, 0, 'application-codeset');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (21, 'System Information', 'System Information', 'sidebar', 'LEVEL_1', 6, NULL, 'System Information', 'System Information', false, NULL, 15, 0, NULL);
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (22, 'System Configuration', 'System Configuration', 'sidebar', 'LEVEL_1', 1, NULL, 'System Configuration', 'System Configuration', true, NULL, 21, 0, 'system-configuration');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (23, 'Health Checks', 'Health Checks', 'sidebar', 'LEVEL_1', 2, NULL, 'Health Checks', 'Health Checks', false, NULL, 21, 0, 'Health Checks');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (24, 'Application Metrics', 'Application Metrics', 'sidebar', 'LEVEL_1', 3, NULL, 'Application Metrics', 'Application Metrics', false, NULL, 21, 0, 'application-matrics');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (25, 'Log Configurations', 'Log Configurations', 'sidebar', 'LEVEL_1', 4, NULL, 'Log Configurations', 'Log Configurations', NULL, NULL, 21, 0, 'log-configuration');
INSERT INTO menu (id, name, state, type, level, "position", icon, tooltip, breadcrumb, disabled, module_id, parent_id, archived, url) OVERRIDING SYSTEM VALUE VALUES (26, 'Menu Management', 'Menu Management', 'sidebar', 'LEVEL_1', 1, NULL, 'Menu Management', 'Menu Management', false, NULL, 15, 0, 'menu');


SELECT pg_catalog.setval('menu_id_seq', (26), true);
